### ISSUE TITLE
[UI] Dialogflow & Actions on google 튜토리얼 진행

### ISSUE THREAD

**Issue by tea7day** [nomins/go-build#3]
### 튜토리얼

- [x] [Build Your First App with Dialogflow](https://developers.google.com/actions/dialogflow/first-app)
- [x] [Hands-on with Dialogflow & Google Assistant: Writing your first Conversation Agent](https://rominirani.com/hands-on-with-api-ai-google-assistant-writing-your-first-conversation-agent-a6a7dcdaba27)

## 한글 자료

- [x] [구글 AI 플랫폼 Dialogflow, 눈으로 따라하며 배우기](http://www.kwangsiklee.com/ko/2018/01/%EA%B5%AC%EA%B8%80-ai-%ED%94%8C%EB%9E%AB%ED%8F%BC-dialogflow-%EB%88%88%EC%9C%BC%EB%A1%9C-%EB%94%B0%EB%9D%BC%ED%95%98%EB%A9%B0-%EB%B0%B0%EC%9A%B0%EA%B8%B0/)
- [x] [steemit chatbot 을 만들어 보자 - (1) 챗봇 개념 이해하기](https://steemit.com/kr/@adana/steemit-chatbot-1 )
- [x] [누군가에겐 필요한 기록 #2. Dialogflow 활용을 통한 챗봇의 구성과 소통의 이해](http://evey.hol.es/?p=90)
- [x] [1시간만에 만드는 음성인식 인공지능 챗봇 구글코리아 정명훈 SA](https://www.slideshare.net/rockplace/1-sa)

**Comment by tea7day** [comment]
### 튜토리얼 후기

[Hands-on with Dialogflow & Google Assistant: Writing your first Conversation Agent](https://rominirani.com/hands-on-with-api-ai-google-assistant-writing-your-first-conversation-agent-a6a7dcdaba27)

### 소감

Dialogflow에서 챗봇을 만드는 UI는 굉장히 직관적이고 조작하기 쉽다. 
단, 챗봇 구성요소에 대한 이해가 쉽지 않다. 
예를 들어, 챗봇을 구성하려면 Intent, Entity, Utterance, Response, Training, Action, Fullfilment등에 대한 개념을 잘 알고 있어야한다. 

각각의 개념이 아직 잘 이해가 안되지만, 튜토리얼을 2개정도 해보니까 전체 프로세스에 대한 감은 오는 거 같다. 
2~3개의 튜토리얼을 더 진행해보고 중요 개념에 대해 문서도 같이 보면서 이해를 높여야겠다.

### 주의

튜토리얼이 3월10일에 업데이트되었지만 그사이에 dialogflow api가 변경됬는지 튜토리얼과 다른부분이 있다. 
- fullfillment request json의 필드값이 다르다. req.body.result -> req.body.queryReuslt

**Comment by deokju** [comment]
2개의 튜토리얼을 벌써 하다니 대단하군.
그런데 Utterance 이게 뭐야? 나는 저게 제일 궁금하네.

**Comment by tea7day** [comment]
챗봇이 아무래도 언어에 연관된거다 보니까 언어 자체에 대한 이해가 필요하더라고...
`utterance`는 사전적의미는 말하기,발언이란 뜻인데, 챗봇 플랫폼마다 이 뜻이 쓰이는 용도는 조금 달라.
예를 들어 `Amazon lex`라는 챗봇 플랫폼에서는 `utterance`가 챗봇을 깨우는 문구로 쓰이더라고
`Google dialogflow`에서는 별다른 의미가 없공ㅋ
